channels:
  - bioconda
  - conda-forge
dependencies:
  - snakemake-minimal =5.2.4
  - python =3.6
  - gatk4 =4.0.11.0
  - hisat2 =2.1.0
  - samtools =1.9
  - sra-tools
  - stringtie
  - biopython
  - git
  - maven
  - fastqc
  - skewer
  - star =2.7.0f-0
  - numpy
  - biopython
  - bcbio-gff
  - pandas
  - rsem =1.3.2-0
#- vcftools =0.1.15
